include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    inference_failure_on_function_invocation: false
    avoid_dynamic_calls: false
    no_default_cases: false
    strict_raw_type: false
    use_setters_to_change_properties: false